# Generated by Django 3.1 on 2020-08-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('user', models.CharField(max_length=100)),
                ('bio', models.TextField(default='no bio....', max_length=1000)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('image', models.ImageField(default='avatar.png', upload_to='img/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
