# Generated by Django 3.1 on 2020-08-31 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200829_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='movies')),
                ('language', models.CharField(max_length=20)),
                ('cast', models.CharField(max_length=100)),
                ('movie_trailer', models.FileField(upload_to='movies/%Y/%m/%d/')),
                ('views_count', models.IntegerField(default=0)),
                ('year_of_production', models.DateField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
