# Generated by Django 3.1 on 2020-11-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_movieview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieView',
        ),
    ]
